"""MCP server: every sp CLI command exposed as a tool over stdio JSON-RPC.

Tools are generated by introspecting the argparse parser from cli.build_parser(),
so the tool surface always matches the CLI exactly. Calls are executed in-process
via cli.main(argv): the same config, SyncStore, mutations and op-log path as the
CLI, so every sync invariant (vectorClock, recentOps, backups) is inherited.

Transport: newline-delimited JSON-RPC 2.0 on stdin/stdout (MCP stdio).
stdout carries only protocol frames; command output is captured into the
tool result, and stdin is swapped out during dispatch so no command can
ever read the protocol stream (interactive confirmations become errors
telling the caller to pass yes=true).
"""

from __future__ import annotations

import argparse
import contextlib
import fnmatch
import io
import json
import sys

from sp_cli import __version__, cli

PROTOCOL_VERSION = "2025-06-18"
SUPPORTED_VERSIONS = ("2025-06-18", "2025-03-26", "2024-11-05")

SERVER_INFO = {"name": "sp-mcp", "version": __version__}

INSTRUCTIONS = """\
Tools for Super Productivity (tasks, planner, time tracking, repeats, notes,
boards, counters, calendars) via its WebDAV sync file. Every write syncs to the
user's phone, so treat writes as real.

Conventions:
- Task/note/etc. ids accept unique prefixes (first 4-6 chars are enough).
- Listing tools accept json=true — prefer it when you need to parse output.
- Destructive tools (delete, *_rm, archive, bulk) ask for confirmation:
  pass yes=true to proceed. Without it they fail rather than prompt.
- Dates are YYYY-MM-DD (or today/tomorrow/+N where documented), durations are
  like 30m / 1.5h, times of day are HH:MM.
- sp_add titles support short syntax: +project #tag @tomorrow 9:00 ~30m.
"""

READ_ONLY = {
    "list", "show", "backlog", "today", "plan-show", "agenda", "current",
    "worklog", "repeats", "projects", "tags", "notes", "note-show", "boards",
    "counters", "providers", "metrics", "archived", "attachments", "pull",
    "doctor",
}

DESTRUCTIVE = {"delete", "archive", "project-archive", "bulk", "untrack", "init"}


def _is_destructive(command: str) -> bool:
    return command in DESTRUCTIVE or command.endswith("-rm")


def tool_name(command: str) -> str:
    return "sp_" + command.replace("-", "_")


def _subparsers_action(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    raise RuntimeError("CLI parser has no subcommands")


def iter_subcommands(parser: argparse.ArgumentParser):
    """Yields (command_name, subparser, help_text) for every CLI command."""
    sub = _subparsers_action(parser)
    helps = {pseudo.dest: pseudo.help or "" for pseudo in sub._choices_actions}
    for name, sp in sub.choices.items():
        yield name, sp, helps.get(name, "")


def _property_schema(action: argparse.Action) -> dict:
    if isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction)):
        item: dict = {"type": "boolean"}
    elif action.type is int:
        item = {"type": "integer"}
    elif action.type is float:
        item = {"type": "number"}
    else:
        item = {"type": "string"}
    if action.choices is not None:
        item["enum"] = list(action.choices)

    is_array = isinstance(action, argparse._AppendAction) or action.nargs in ("+", "*")
    if is_array:
        schema: dict = {"type": "array", "items": item}
        if action.nargs == "+":
            schema["minItems"] = 1
    else:
        schema = item
    if action.help:
        schema["description"] = action.help
    return schema


def _actions(subparser: argparse.ArgumentParser) -> list[argparse.Action]:
    return [
        a for a in subparser._actions if not isinstance(a, argparse._HelpAction)
    ]


def tool_schema(command: str, subparser: argparse.ArgumentParser, help_: str) -> dict:
    properties: dict[str, dict] = {}
    required: list[str] = []
    # positionals first so the schema reads like the CLI usage line
    ordered = sorted(_actions(subparser), key=lambda a: bool(a.option_strings))
    for action in ordered:
        if action.dest in properties:
            raise RuntimeError(f"{command}: duplicate parameter {action.dest}")
        properties[action.dest] = _property_schema(action)
        if not action.option_strings:
            if action.nargs not in ("?", "*"):
                required.append(action.dest)
        elif action.required:
            required.append(action.dest)
    input_schema: dict = {
        "type": "object",
        "properties": properties,
        "additionalProperties": False,
    }
    if required:
        input_schema["required"] = required
    return {
        "name": tool_name(command),
        "description": help_ or command,
        "inputSchema": input_schema,
        "annotations": {
            "title": f"sp {command}",
            "readOnlyHint": command in READ_ONLY,
            "destructiveHint": _is_destructive(command),
        },
    }


def _long_flag(action: argparse.Action) -> str:
    for opt in action.option_strings:
        if opt.startswith("--"):
            return opt
    return action.option_strings[0]


def _scalar(value) -> str:
    # JSON clients may send 5.0 for an integer parameter
    if isinstance(value, float) and value.is_integer():
        value = int(value)
    return str(value)


def build_argv(command: str, subparser: argparse.ArgumentParser, arguments: dict) -> list[str]:
    """Maps validated tool arguments back onto a CLI argv."""
    known = {a.dest: a for a in _actions(subparser)}
    unknown = set(arguments) - set(known)
    if unknown:
        raise ToolError(f"unknown argument(s): {', '.join(sorted(unknown))}")
    options: list[str] = []
    positionals: list[str] = []
    for action in _actions(subparser):
        if action.dest not in arguments or arguments[action.dest] is None:
            continue
        value = arguments[action.dest]
        if not action.option_strings:
            if isinstance(value, list):
                positionals.extend(_scalar(v) for v in value)
            else:
                positionals.append(_scalar(value))
            continue
        flag = _long_flag(action)
        if isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction)):
            if isinstance(value, str):
                value = value.strip().lower() in ("1", "true", "yes", "on")
            if value:
                options.append(flag)
        elif isinstance(value, list):
            # --flag=value keeps dash-leading values from parsing as options
            options.extend(f"{flag}={_scalar(item)}" for item in value)
        else:
            options.append(f"{flag}={_scalar(value)}")
    if positionals:
        # "--" protects dash-leading positionals and, as argv[1], makes the
        # argv immune to cli._rewrite_argv alias collisions
        return [command, *options, "--", *positionals]
    return [command, *options]


class ToolError(Exception):
    pass


class SpMcpServer:
    def __init__(
        self,
        include: list[str] | None = None,
        exclude: list[str] | None = None,
        read_only: bool = False,
    ):
        parser = cli.build_parser()
        self.commands: dict[str, tuple[argparse.ArgumentParser, str]] = {}
        for name, sp, help_ in iter_subcommands(parser):
            if read_only and name not in READ_ONLY:
                continue
            if include and not any(fnmatch.fnmatch(name, pat) for pat in include):
                continue
            if exclude and any(fnmatch.fnmatch(name, pat) for pat in exclude):
                continue
            self.commands[tool_name(name)] = (sp, help_)
        self.tools = [
            tool_schema(tname.removeprefix("sp_").replace("_", "-"), sp, help_)
            for tname, (sp, help_) in self.commands.items()
        ]

    # -- tool execution ----------------------------------------------------

    def call_tool(self, name: str, arguments: dict) -> tuple[str, bool]:
        """Returns (text, is_error)."""
        if name not in self.commands:
            raise ToolError(f"unknown tool: {name}")
        subparser, _ = self.commands[name]
        command = name.removeprefix("sp_").replace("_", "-")
        argv = build_argv(command, subparser, arguments or {})
        out, err = io.StringIO(), io.StringIO()
        real_stdin = sys.stdin
        sys.stdin = io.StringIO("")  # no command may read the protocol stream
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                code = cli.main(argv, rewrite=False)
        except SystemExit as e:  # argparse rejected the argv
            code = e.code if isinstance(e.code, int) else 2
        except EOFError:
            return (
                f"'{command}' asks for interactive confirmation; "
                "pass yes=true to proceed",
                True,
            )
        except Exception as e:  # noqa: BLE001 — a tool crash must not kill the server
            return (f"{command} failed: {type(e).__name__}: {e}", True)
        finally:
            sys.stdin = real_stdin
        stdout, stderr = out.getvalue(), err.getvalue()
        if code != 0:
            text = "\n".join(part for part in (stderr.strip(), stdout.strip()) if part)
            return (text or f"{command}: exit code {code}", True)
        return (stdout if stdout.strip() else stdout + stderr, False)

    # -- JSON-RPC ----------------------------------------------------------

    def handle(self, msg: dict) -> dict | None:
        """Returns a response dict, or None for notifications."""
        msg_id = msg.get("id")
        method = msg.get("method")
        is_notification = "id" not in msg

        def result(payload: dict) -> dict:
            return {"jsonrpc": "2.0", "id": msg_id, "result": payload}

        def error(code: int, message: str) -> dict | None:
            if is_notification:
                return None
            return {
                "jsonrpc": "2.0",
                "id": msg_id,
                "error": {"code": code, "message": message},
            }

        if not isinstance(method, str):
            return error(-32600, "invalid request: method must be a string")
        params = msg.get("params") or {}
        if method == "initialize":
            requested = params.get("protocolVersion")
            version = requested if requested in SUPPORTED_VERSIONS else PROTOCOL_VERSION
            return result(
                {
                    "protocolVersion": version,
                    "capabilities": {"tools": {"listChanged": False}},
                    "serverInfo": SERVER_INFO,
                    "instructions": INSTRUCTIONS,
                }
            )
        if method == "ping":
            return result({})
        if method == "tools/list":
            return result({"tools": self.tools})
        if method == "tools/call":
            name = params.get("name", "")
            arguments = params.get("arguments") or {}
            try:
                text, is_error = self.call_tool(name, arguments)
            except ToolError as e:
                return error(-32602, str(e))
            payload = {"content": [{"type": "text", "text": text}]}
            if is_error:
                payload["isError"] = True
            return result(payload)
        if is_notification:  # notifications/initialized, notifications/cancelled, ...
            return None
        return error(-32601, f"method not found: {method}")

    def _handle_frame(self, msg) -> list:
        """One decoded stdin frame → the frames to write back (0..n).

        A non-empty JSON-RPC batch yields one frame that is itself an array;
        an empty or malformed frame yields a single -32600 object (per spec).
        """

        def invalid(what) -> dict:
            return {
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32600, "message": f"invalid request: {what}"},
            }

        if isinstance(msg, list):  # JSON-RPC batch (pre-2025-06-18 clients)
            if not msg:
                return [invalid("empty batch")]
            responses = []
            for item in msg:
                if isinstance(item, dict):
                    resp = self.handle(item)
                    if resp is not None:
                        responses.append(resp)
                else:
                    responses.append(invalid("batch items must be objects"))
            return [responses] if responses else []
        if not isinstance(msg, dict):
            return [invalid("expected an object")]
        resp = self.handle(msg)
        return [resp] if resp is not None else []

    def serve(self, stdin=None, stdout=None) -> int:
        stdin = stdin if stdin is not None else sys.stdin.buffer
        stdout = stdout if stdout is not None else sys.stdout.buffer

        def send(obj: dict) -> None:
            stdout.write(json.dumps(obj, ensure_ascii=False).encode("utf-8") + b"\n")
            stdout.flush()

        for line in stdin:
            line = line.strip()
            if not line:
                continue
            try:
                msg = json.loads(line)
            except json.JSONDecodeError as e:
                send(
                    {
                        "jsonrpc": "2.0",
                        "id": None,
                        "error": {"code": -32700, "message": f"parse error: {e}"},
                    }
                )
                continue
            try:
                responses = self._handle_frame(msg)
            except Exception as e:  # noqa: BLE001 — protocol loop must survive
                print(f"sp-mcp: internal error: {e}", file=sys.stderr)
                msg_id = msg.get("id") if isinstance(msg, dict) else None
                responses = [
                    {
                        "jsonrpc": "2.0",
                        "id": msg_id,
                        "error": {"code": -32603, "message": f"internal error: {e}"},
                    }
                ]
            for response in responses:
                send(response)
        return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="sp-mcp", description="MCP stdio server for sp-cli"
    )
    p.add_argument(
        "--include",
        action="append",
        metavar="GLOB",
        help="only expose commands matching this glob (repeatable)",
    )
    p.add_argument(
        "--exclude",
        action="append",
        metavar="GLOB",
        help="hide commands matching this glob (repeatable)",
    )
    p.add_argument(
        "--read-only",
        action="store_true",
        help="expose only read-only tools (no writes possible); recommended "
        "for autonomous or untrusted agents",
    )
    p.add_argument(
        "--list-tools",
        action="store_true",
        help="print the generated tool names and exit",
    )
    args = p.parse_args(argv)
    server = SpMcpServer(
        include=args.include, exclude=args.exclude, read_only=args.read_only
    )
    if args.list_tools:
        for tool in server.tools:
            print(f"{tool['name']}\t{tool['description']}")
        print(f"# {len(server.tools)} tools", file=sys.stderr)
        return 0
    return server.serve()


if __name__ == "__main__":
    sys.exit(main())
